services:
  service-pg:
    image: bitnami/postgresql
    container_name: nlw_connect
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  service-redis:
    image: bitnami/redis
    ports:
      - ${POSTGRES_PORT_REDIS}:${POSTGRES_PORT_REDIS}
    environment:
      - ALLOW_EMPTY_PASSWORD=yes